---
- hosts: localhost
  tasks:
    - name: Import Vars...
      include_vars:
        file: vyos-l1.yml
    - name: Combine vyos...
      template: 
        src: templates/vyos-leaf.j2
        dest: vyos-l1-compiled.conf
