---
- hosts: localhost
  tasks:
    - name: Import Vars...
      include_vars:
        file: vyos-s1.yml
    - name: Combine vyos...
      template: 
        src: templates/vyos-spine.j2
        dest: vyos-s1-compiled.conf
